language: go

go:
  - 1.9.x

env:
  global:
  - secure: Lp2wP7kEuHh73359WXHlkrlpVfXfEvAnHIe6fq1M7cZg+zco6GH41PW+1iPm/Z4UlS382qRT/3QY6GntFDUBVGeGt5xmNaCq3jQAhG5HMqWvSod5OnQK4YxVxzF1osWcBanwK930TMR/aIW1V15P9/AUvMYN1cDrqxQ7+ObknTC4aS42vKCb66CyfJrAMNAfoeRqlz16fiJHvkIHZ31T7M9fddp9NjWpJvTjqoX0OD5gp1Dn6HNk5sesd0loWfwSj0HsZpwuYI173i1WVEkljfIshGAtSqHGONg8+CCrBH7FeJv2uJ/sETYIUK0XorIvYW1/luWrR1/+FT6hKz07+qbi9IKDR8FvZtJrTakH8mI8rrBQF5DNaUPqlZmIRVs2BZQTx2nSYBWuRcrHvwv9btpobDXqZ/XO2Kux426z+LNSVACsqWono5mlPd9Vi/AsyT7f4/RtLDSNwo354xskQYqy8wsJA0ri5IFXZ0aaVFUO4eHVatzP1RAVTCGJzN+YIdC1yZ4NQyydaaALH3I+b8II6rBfOfstKb/vBNVjNEMWKvxlKB3XKhmAbGD56beY+Vug/7IqtADN4w07p7HzarR4HJyGua1851onmduh0MyuZajQKK+JKDlFAMQhLPSynjQWUqp/BPRwss1PwZ+sKfByGW7ZaJLUKkkbkG3bjdg=

services:
  - docker

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/karalabe/xgo
  - go env && pwd

after_success:
  - sh ./bin/set_tags.sh

script:
  - ./bin/travis.sh --init
  - ./bin/travis.sh --build
  - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: $HOME/smart-home-node.tar.gz
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: e154/smart-home-node
  branches:
    only:
      - master
      - /^v\d+(\.\d+)+$/

notifications:
  email:
    on_success: never
    on_failure: always