language: go

go:
  - 1.7.x

before_install:
  - go get github.com/FiloSottile/gvt
  - go env && pwd

after_success:
  - sh ./bin/set_tags.sh

script:
  - ./bin/make.sh --init
  - ./bin/make.sh --build

deploy:
  provider: releases
  api_key:
    secure: gcRudQPYa9eK4hbSauoR4YME34v4TBKZy/DutR+UUAJdKWl+EEK+armuqtgmiyzEmp0SPsv1bxB+It6jgmw3BC4vdY59I/jwaR1zRfBQkO4IGf6RajFAKEILkdfWPWkjGlXhLgOrfJ4M3oHUq4xl8kE402KptWCZWPARU1/gMluFKZUgpMShuT/DWRPhifqRvJol0xXSzrRVP18NKMyydoe2MmnQDZUINES05K/eAiQJJktqHp7HHiHc8B6Y5ksybTZ8b199D0PAdulaSPIa640QPE1sPZauq8nouo/2MSQOEN5tIx9Hw20fv8rlAKlA8EQR6DEea0OljFqJniiS5JA7FRJYUnMo9WptvaeLSlWvc3Z9G2FAg56DNbezTh29AQaxq8ZawlHSQP3WzP4tn4ESDYT1ITOqLROYG2GPNwEJEiEXhf29h1hfz+FB5dlf2Fen+Zo0MtxnsnvCsB2ebDm6NOZMyuWAFjwqJZ37RWKybVVC/PGDDvQnZT6D57l/mDDC7/2F1RlBlhcC3pIpbAEQcNCYujQHxWodP8It+QMvt7k57grXW/PXnbWhMskvput7RrtqnxuOoMJ+7eGlwL54ii90YdWw72dBXXWTj9yfkHnEjP8GPbr9nMZ+oNFi8CSC4pBJTUFpKmfkkzBwbFiNdYTM7KDyQ/MbKP48ATU=
  file: $HOME/node-release.tar.gz
  skip_cleanup: true
  on:
    branch: master
    repo: e154/smart-home-node

notifications:
  email:
    on_success: never
    on_failure: always