language: go

go:
  - 1.7.x

env:
  global:
  - secure: Lp2wP7kEuHh73359WXHlkrlpVfXfEvAnHIe6fq1M7cZg+zco6GH41PW+1iPm/Z4UlS382qRT/3QY6GntFDUBVGeGt5xmNaCq3jQAhG5HMqWvSod5OnQK4YxVxzF1osWcBanwK930TMR/aIW1V15P9/AUvMYN1cDrqxQ7+ObknTC4aS42vKCb66CyfJrAMNAfoeRqlz16fiJHvkIHZ31T7M9fddp9NjWpJvTjqoX0OD5gp1Dn6HNk5sesd0loWfwSj0HsZpwuYI173i1WVEkljfIshGAtSqHGONg8+CCrBH7FeJv2uJ/sETYIUK0XorIvYW1/luWrR1/+FT6hKz07+qbi9IKDR8FvZtJrTakH8mI8rrBQF5DNaUPqlZmIRVs2BZQTx2nSYBWuRcrHvwv9btpobDXqZ/XO2Kux426z+LNSVACsqWono5mlPd9Vi/AsyT7f4/RtLDSNwo354xskQYqy8wsJA0ri5IFXZ0aaVFUO4eHVatzP1RAVTCGJzN+YIdC1yZ4NQyydaaALH3I+b8II6rBfOfstKb/vBNVjNEMWKvxlKB3XKhmAbGD56beY+Vug/7IqtADN4w07p7HzarR4HJyGua1851onmduh0MyuZajQKK+JKDlFAMQhLPSynjQWUqp/BPRwss1PwZ+sKfByGW7ZaJLUKkkbkG3bjdg=

before_install:
  - go get github.com/FiloSottile/gvt
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go env && pwd

after_success:
  - sh ./bin/set_tags.sh

script:
  - ./bin/make.sh --init
  - ./bin/make.sh --build
  - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN

deploy:
  provider: releases
  api_key:
    secure: gcRudQPYa9eK4hbSauoR4YME34v4TBKZy/DutR+UUAJdKWl+EEK+armuqtgmiyzEmp0SPsv1bxB+It6jgmw3BC4vdY59I/jwaR1zRfBQkO4IGf6RajFAKEILkdfWPWkjGlXhLgOrfJ4M3oHUq4xl8kE402KptWCZWPARU1/gMluFKZUgpMShuT/DWRPhifqRvJol0xXSzrRVP18NKMyydoe2MmnQDZUINES05K/eAiQJJktqHp7HHiHc8B6Y5ksybTZ8b199D0PAdulaSPIa640QPE1sPZauq8nouo/2MSQOEN5tIx9Hw20fv8rlAKlA8EQR6DEea0OljFqJniiS5JA7FRJYUnMo9WptvaeLSlWvc3Z9G2FAg56DNbezTh29AQaxq8ZawlHSQP3WzP4tn4ESDYT1ITOqLROYG2GPNwEJEiEXhf29h1hfz+FB5dlf2Fen+Zo0MtxnsnvCsB2ebDm6NOZMyuWAFjwqJZ37RWKybVVC/PGDDvQnZT6D57l/mDDC7/2F1RlBlhcC3pIpbAEQcNCYujQHxWodP8It+QMvt7k57grXW/PXnbWhMskvput7RrtqnxuOoMJ+7eGlwL54ii90YdWw72dBXXWTj9yfkHnEjP8GPbr9nMZ+oNFi8CSC4pBJTUFpKmfkkzBwbFiNdYTM7KDyQ/MbKP48ATU=
  file: $HOME/smart-home-node.tar.gz
  skip_cleanup: true
  on:
    branch: master
    repo: e154/smart-home-node

notifications:
  email:
    on_success: never
    on_failure: always